trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

variables:
  imageName: 'flask-static-app'

steps:
- task: DockerInstaller@0
  inputs:
    dockerVersion: 'latest'

- task: Docker@2
  inputs:
    containerRegistry: 'acr-Connection'
    repository: '$(imageName)'
    command: 'buildAndPush'
    Dockerfile: '**/Dockerfile'
    tags: |
      latest
